# Generated by Django 3.2.8 on 2024-07-05 15:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'photo'},
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_name',
            field=models.CharField(default=datetime.datetime(2024, 7, 5, 15, 4, 55, 210635, tzinfo=utc), max_length=100, verbose_name='Photo name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='model_field',
            field=models.ImageField(upload_to='photos/', verbose_name='mphoto'),
        ),
    ]
